class RanOutError(Exception):
    def __init__(self):
        pass

